name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: Eukky/eukky.github.io@dev
      env:
        ACCESS_TOKEN: ${{ secrets.SECRET_KEY }}
        TARGET_REPO: eukky/eukky.github.io
        TARGET_BRANCH: release
        BUILD_SCRIPT: npm && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist
